 CREATE DATABASE LOJA_HARDWARE;

USE LOJA_HARDWARE;

CREATE TABLE PRODUTO(
  IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(60) NOT NULL,
  VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO PRODUTO VALUES(NULL, 'SSD 1TB', '500.50');
INSERT INTO PRODUTO VALUES(NULL,'HD 500GB', '250.00');
INSERT INTO PRODUTO VALUES(NULL, 'MEMÓRIA DRR4 8GB','300.00');
INSERT INTO PRODUTO VALUES(NULL, 'PROCESSADOR RYZEN 7', '1500.00');
INSERT INTO PRODUTO VALUES(NULL, 'RADEON GRAPHICS AMD', '600.00');



  CREATE DATABASE BACKUP_HARDWARE;

USE BACKUP_HARDWARE;

CREATE TABLE BACKUP_PRODUTO(
  IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
  IDPRODUTO INT,
  NOME VARCHAR(60) NOT NULL,
  VALOR FLOAT(10,2) NOT NULL,
  VALOR_ATUAL FLOAT(10, 2),
  DATA_HORA DATETIME,
  USUARIO VARCHAR(30),
  EVENTO CHAR(6)


);

-- EXEMPLO DO COMANDO NOW()
SELECT IDPRODUTO, NOME, VALOR, NOW() AS "DATA_HORA EM QUE COMANDO FOI EXECUTADO" 
FROM PRODUTO;


-- OU SEJA VAI MOSTRAR DATA E HORA QUE EU EXECUTEI ESSE SELECT, POR EXEMPLO
-- DATETIME = DATE = DATA
-- TIME = HORA  

USE LOJA_HARDWARE;
DELIMITER $
STATUS 

CREATE TABLE BACKUP_PRODUTO(
  IDBACKUP INT PRIMARY KEY AUTO_INCRMENT;
  IDPRODUTO INT,
  NOME VARCHAR(60) NOT NULL,
  VALOR FLOAT(10,2) NOT NULL,
  VALOR_ATUAL FLOAT(10, 2),
  DATA_HORA DATETIME,
  USUARIO VARCHAR(30),
  EVENTO CHAR(6)


);
CREATE TRIGGER BACKUP_TABLE_PRODUTO
AFTER UPDATE ON PRODUTO
FOR EACH ROW 

BEGIN 

    INSERT INTO BACKUP_HARDWARE.BACKUP_PRODUTO VALUES(NULL, OLD.IDPRODUTO,
                                                            OLD.NOME, 
                                                            OLD.VALOR,
                                                            NEW.VALOR,
                                                            NOW(),
                                                            CURRENT_USER(),
                                                            'UPDATE');

END 
$

DELIMITER ;

STATUS 

USE LOJA_HARDWARE;

SELECT IDPRODUTO, NOME, VALOR FROM PRODUTO
WHERE IDPRODUTO = 5;

+-----------+---------------------+--------+
| IDPRODUTO | NOME                | VALOR  |
+-----------+---------------------+--------+
|         5 | RADEON GRAPHICS AMD | 600.00 |
+-----------+---------------------+--------+
UPDATE PRODUTO
SET VALOR = '900.00'
WHERE IDPRODUTO = 5;

SELECT IDBACKUP, IDPRODUTO, NOME, 
      VALOR, VALOR_ATUAL, 
      DATA_HORA, USUARIO, 
      EVENTO FROM BACKUP_HARDWARE.BACKUP_PRODUTO;

