CREATE DATABASE OFICINA;

USE OFICINA;


CREATE TABLE CLIENTE(
  IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  SEXO ENUM('F', 'M') NOT NULL,
  ID_CARRO INT UNIQUE

);

CREATE TABLE TELEFONE(
  IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
  TIPO ENUM('CEL', 'RES', 'COM') NOT NULL,
  NUMERO VARCHAR(20) NOT NULL,
  ID_CLIENTE INT

);


CREATE TABLE CARRO(
  IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
  MODELO VARCHAR(40) NOT NULL,
  PLACA VARCHAR(30) NOT NULL UNIQUE,
  ID_MARCA INT

);


CREATE TABLE MARCA(
  IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
  MARCA VARCHAR(30) NOT NULL UNIQUE

);

CREATE TABLE COR(
  IDCOR INT PRIMARY KEY AUTO_INCREMENT,
  COR VARCHAR(20) UNIQUE

);

/ * TABELA ASSOCIATION */
CREATE TABLE CARRO_COR(
  ID_CARRO INT,
  ID_COR INT,

  PRIMARY KEY(ID_CARRO, ID_COR)

);


ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);


ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY (ID_CARRO) REFERENCES CARRO (IDCARRO);


ALTER TABLE CARRO ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY (ID_MARCA) REFERENCES MARCA (IDMARCA);

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_CARRO
FOREIGN KEY (ID_CARRO) REFERENCES CARRO (IDCARRO);

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_COR
FOREIGN KEY (ID_COR) REFERENCES COR (IDCOR);


 /* COMEÇAR O INSERT PELA TABELA MAIS IMPORTANTE DO BANCO, NESSE CASO TABELA CARRO */
INSERT INTO CARRO VALUES(NULL,' Gol', 'HTM-2074',1);
INSERT INTO CARRO VALUES(NULL,' Uno', 'JGE-7513', 2);
INSERT INTO CARRO VALUES(NULL,'Palio', 'JSK-9985',3);
INSERT INTO CARRO VALUES(NULL,' Fox ', 'MRZ-8349',4);
INSERT INTO CARRO VALUES(NULL,' Siena ', 'GTV-9456',5);
INSERT INTO CARRO VALUES(NULL,'Celta', 'JMW-6502',6);
INSERT INTO CARRO VALUES(NULL,'HB20 ', 'CJH-7730', 7);
INSERT INTO CARRO VALUES(NULL,' Voyage', 'HEH-7396',8);
INSERT INTO CARRO VALUES(NULL,'Corsa Sedan ', 'NEG-6127',9);
INSERT INTO CARRO VALUES(NULL,'Onix ', 'ICV-7163',10);


SELECT IDCARRO, MODELO, PLACA, ID_MARCA FROM CARRO;
+---------+--------------+----------+----------+
| IDCARRO | MODELO       | PLACA    | ID_MARCA |
+---------+--------------+----------+----------+
|       1 |  Gol         | HTM-2074 |        1 |
|       2 |  Uno         | JGE-7513 |        2 |
|       3 | Palio        | JSK-9985 |        3 |
|       4 |  Fox         | MRZ-8349 |        4 |
|       5 |  Siena       | GTV-9456 |        5 |
|       6 | Celta        | JMW-6502 |        6 |
|       7 | HB20         | CJH-7730 |        7 |
|       8 |  Voyage      | HEH-7396 |        8 |
|       9 | Corsa Sedan  | NEG-6127 |        9 |
|      10 | Onix         | ICV-7163 |       10 |
+---------+--------------+----------+----------+

/* INSERT NA TABELA MARCA */

INSERT INTO MARCA VALUES(NULL,' Gol');
INSERT INTO MARCA VALUES(NULL,' Uno');
INSERT INTO MARCA VALUES(NULL,'Palio');
INSERT INTO MARCA VALUES(NULL,' Fox ');
INSERT INTO MARCA VALUES(NULL,' Siena ');
INSERT INTO MARCA VALUES(NULL,'Celta');
INSERT INTO MARCA VALUES(NULL,'HB20 ');
INSERT INTO MARCA VALUES(NULL,' Voyage');
INSERT INTO MARCA VALUES(NULL,'Corsa Sedan ');
INSERT INTO MARCA VALUES(NULL,'Onix ');


SELECT IDMARCA, MARCA FROM MARCA;
+---------+--------------+
| IDMARCA | MARCA        |
+---------+--------------+
|       4 |  Fox         |
|       1 |  Gol         |
|       5 |  Siena       |
|       2 |  Uno         |
|       8 |  Voyage      |
|       6 | Celta        |
|       9 | Corsa Sedan  |
|       7 | HB20         |
|      10 | Onix         |
|       3 | Palio        |
+---------+--------------+

/* INSERT NA TABELA CLIENTE */

INSERT INTO CLIENTE VALUES(NULL,'Luara Passos Quintal', 'luara4363@gmail.com', 'F', 1);
INSERT INTO CLIENTE VALUES(NULL,'Ariana Setúbal Marçal', 'Ariana59686@gmail.com','F',2);
INSERT INTO CLIENTE VALUES(NULL,'Suzana Calado Valido', 'suzana47448@gmail.com','F',3);
INSERT INTO CLIENTE VALUES(NULL,'Leonel Melgaço Quental','leonel4748@outlook.com','M',4);
INSERT INTO CLIENTE VALUES(NULL,'Nathan Casado Moreira', 'nathan4554@outlook.com','M',5);
INSERT INTO CLIENTE VALUES(NULL,'uliano Lopes Pereira','uliano@6466outlook.com','M',6);
INSERT INTO CLIENTE VALUES(NULL,'Filipe Gago Protásio','felipe464645@gmail.com','M',7);
INSERT INTO CLIENTE VALUES(NULL,'João Ouro Negreiros','joaoe8884@gmail.com','M',8);
INSERT INTO CLIENTE VALUES(NULL,'Lena Álvaro Aveiro','lena44ii3@gmail.com','M',9);
INSERT INTO CLIENTE VALUES(NULL,'Karolina Alvarenga Caires','karolina84747@gmail.com','F',10);

SELECT IDCLIENTE, NOME, EMAIL, SEXO, ID_CARRO FROM CLIENTE;


/* INSERT NA TABELA TELEFONE */

INSERT INTO TELEFONE VALUES(NULL,'CEL','(9993836373)',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','(9993836554)',2);
INSERT INTO TELEFONE VALUES(NULL,'COM','(9473673636)',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','(9993836375)',4);
INSERT INTO TELEFONE VALUES(NULL,'CEL','(9993836374)',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','(9993836371)',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','(9993836374)',7);
INSERT INTO TELEFONE VALUES(NULL,'CEL','(9993836378)',8);
INSERT INTO TELEFONE VALUES(NULL,'CEL','(9993836379)',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','(9993836377)',10);

/* INSERT NA TABELA COR */

INSERT INTO COR VALUES(NULL,'verde');
INSERT INTO COR VALUES(NULL,' amarelo');
INSERT INTO COR VALUES(NULL,' preto');
INSERT INTO COR VALUES(NULL,'azul');
INSERT INTO COR VALUES(NULL,'roxo');
INSERT INTO COR VALUES(NULL,'laranja');
INSERT INTO COR VALUES(NULL,' branca');
INSERT INTO COR VALUES(NULL,'vermelho');
INSERT INTO COR VALUES(NULL,' violeta');
INSERT INTO COR VALUES(NULL,'anil');

-- AMANHA FAZER O INSERT NA TABELA CARRO_COR 

/* INSERT NA TABELA CARRO_COR */

INSERT INTO CARRO_COR VALUES(1, 2);
INSERT INTO CARRO_COR VALUES(2, 2);
INSERT INTO CARRO_COR VALUES(1, 4);
INSERT INTO CARRO_COR VALUES(5, 4);
INSERT INTO CARRO_COR VALUES(10, 8);
INSERT INTO CARRO_COR VALUES(3, 9);
INSERT INTO CARRO_COR VALUES(6, 3);
INSERT INTO CARRO_COR VALUES(7, 1);
INSERT INTO CARRO_COR VALUES(8, 9);
