CREATE DATABASE OFICINA;

USE OFICINA;


CREATE TABLE CLIENTE(
  IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  SEXO ENUM('F', 'M') NOT NULL,
  ID_CARRO INT UNIQUE

);

CREATE TABLE TELEFONE(
  IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
  TIPO ENUM('CEL', 'RES', 'COM') NOT NULL,
  NUMERO VARCHAR(20) NOT NULL,
  ID_CLIENTE INT

);


CREATE TABLE CARRO(
  IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
  MODELO VARCHAR(40) NOT NULL,
  PLACA VARCHAR(30) NOT NULL UNIQUE,
  ID_MARCA INT

);


CREATE TABLE MARCA(
  IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
  MARCA VARCHAR(30) NOT NULL UNIQUE

);

CREATE TABLE COR(
  IDCOR INT PRIMARY KEY AUTO_INCREMENT,
  COR VARCHAR(20) UNIQUE

);

/ * TABELA ASSOCIATION */
CREATE TABLE CARRO_COR(
  ID_CARRO INT,
  ID_COR INT,

  PRIMARY KEY(ID_CARRO, ID_COR)

);


ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);


ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY (ID_CARRO) REFERENCES CARRO (IDCARRO);


ALTER TABLE CARRO ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY (ID_MARCA) REFERENCES MARCA (IDMARCA);

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_CARRO
FOREIGN KEY (ID_CARRO) REFERENCES CARRO (IDCARRO);

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_COR
FOREIGN KEY (ID_COR) REFERENCES COR (IDCOR);


/* COMEÇAR O INSERT PELA TABELA MAIS IMPORTANTE DO BANCO, NESSE CASO TABELA CARRO */
INSERT INTO CARRO VALUES(NULL,' Gol', 'HTM-2074')
INSERT INTO CARRO VALUES(NULL,' Uno', 'JGE-7513')
INSERT INTO CARRO VALUES(NULL,'Palio', 'JSK-9985')
INSERT INTO CARRO VALUES(NULL,' Fox ', 'MRZ-8349')
INSERT INTO CARRO VALUES(NULL,' Siena ', 'GTV-9456')
INSERT INTO CARRO VALUES(NULL,'Celta', 'JMW-6502')
INSERT INTO CARRO VALUES(NULL,'HB20 ', 'CJH-7730')
INSERT INTO CARRO VALUES(NULL,' Voyage', 'HEH-7396')
INSERT INTO CARRO VALUES(NULL,'Corsa Sedan ', 'NEG-6127')
INSERT INTO CARRO VALUES(NULL,'Onix ', 'ICV-7163')



