CREATE DATABASE PROJETO;
USE PROJETO;


CREATE TABLE USUARIO(
  IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  SENHA VARCHAR(8) NOT NULL

);

INSERT INTO USUARIO VALUES(NULL,'Rafael da Silva Sales', 'rafaelssss35445@bol', 'rubi345#');

/* PROCEDURE */
 DEMILITER $ 

 STATUS 

 CREATE PROCEDURE DADOS_USUARIO(P_NOME VARCHAR(30), 
                                P_EMAIL VARCHAR(50), 
                                P_SENHA VARCHAR(8))
BEGIN 
    INSERT INTO USUARIO VALUES(NULL, P_NOME, P_EMAIL, P_SENHA);

END 
$
DELIMITER ;

CALL DADOS_USUARIO('Letícia da Silva', 'leticia345@gmail.com','senha343');
CALL DADOS_USUARIO('Maria da Silva', 'maria83646@gmail.com', '12345678');

+-----------+-----------------------+----------------------+----------+
| IDUSUARIO | NOME                  | EMAIL                | SENHA    |
+-----------+-----------------------+----------------------+----------+
|         1 | Rafael da Silva Sales | rafaelssss35445@bol  | rubi345# |
|         2 | Letícia da Silva      | leticia345@gmail.com | senha343 |
|         3 | Maria da Silva        | maria83646@gmail.com | 12345678 |
+-----------+-----------------------+----------------------+----------+


/* A33 - ALTERANDO TABELAS */

CREATE TABLE TABELA(
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
);

-- ADICIONANDO UMA CHAVE PRIMARY KEY 
ALTER TABLE TABELA 
ADD PRIMARY KEY(COLUNA1);

--ADICIONANDO COLUNA SEM POSIÇÃO.
ALTER TABLE TABELA 
ADD COLUNA18 VARCHAR(50);

ALTER TABLE TABELA 
ADD COLUMN COLUNA19 CHAR(3) NOT NULL UNIQUE;

--ADICIONANDO UMA COLUNA COM POSIÇÃO.
ALTER TABLE TABELA 
ADD COLUMN COLUNA20 CHAR(5)
AFTER COLUNA18;

--MODIFICANDO O TIPO DE UM CAMPO

ALTER TABLE TABELA 
MODIFY COLUNA3 CHAR(5) NOT NULL; 

ALTER TABLE PESSOA
MODIFY COLUNA1 INT NOT NULL; 

--RENOMEANDO O NOME DA TABELA
ALTER TABLE TABELA 
RENAME PESSOA;

CREATE TABLE TIME(
  IDTIME INT PRIMARY KEY AUTO_INCREMENT,
  NOME_TIME VARCHAR(50) NOT NULL,
  IDCLIENTE INT UNIQUE

);

ALTER TABLE TIME 
ADD FOREIGN KEY(IDCLIENTE)
REFERENCES PESSOA(COLUNA1);

INSERT INTO PESSOA VALUES(1, '34', '35', '45', '455', '45');


INSERT INTO TIME VALUES(NULL, 'CORINTHIANS',1);

+----------+-------------+------+-----+---------+-------+
| Field    | Type        | Null | Key | Default | Extra |
+----------+-------------+------+-----+---------+-------+
| COLUNA1  | int         | NO   | PRI | NULL    |       |
| COLUNA2  | varchar(30) | YES  |     | NULL    |       |
| COLUNA3  | char(5)     | NO   |     | NULL    |       |
| COLUNA18 | varchar(50) | YES  |     | NULL    |       |
| COLUNA20 | char(5)     | YES  |     | NULL    |       |
| COLUNA19 | char(3)     | NO   | UNI | NULL    |       |
+----------+-------------+------+-----+---------+-------+

SELECT COLUNA1, COLUNA2, COLUNA3, COLUNA18, COLUNA20, COLUNA19,
NOME_TIME
FROM PESSOA
INNER JOIN TIME
ON COLUNA1 = IDCLIENTE;

/* VERIFICAR AS CHAVES */
SHOW CREATE TABLE TIME;

/* A34 - ORGANIZAÇÃO DE CHAVES - CONSTRAINT (REGRA) */


CREATE TABLE JOGADOR(
  IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(20) NOT NULL
);

CREATE TABLE TIMES(
  IDTIME INT PRIMARY KEY AUTO_INCREMENT,
  NOMETIME VARCHAR(40) NOT NULL,
  ID_JOGADOR INT UNIQUE,

  FOREIGN KEY (ID_JOGADOR)
  REFERENCES JOGADOR(IDJOGADOR)

);


INSERT INTO JOGADOR VALUES(NULL,'GUERRERO');
INSERT INTO TIMES VALUES(NULL,'FLAMENGO',1);

SELECT IDJOGADOR, NOME, NOMETIME
FROM JOGADOR 
  INNER JOIN TIMES 
  ON IDJOGADOR = ID_JOGADOR;

  SHOW CREATE TABLE JOGADOR;

  SHOW CREATE TABLE TIMES;











-- 







